# Generated by Django 5.1.4 on 2024-12-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='index/img')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
