# Generated by Django 5.1.4 on 2024-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_of_offres_location_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='direct',
            name='rating',
            field=models.FloatField(),
        ),
    ]
