# Generated by Django 5.1.4 on 2024-12-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_direct_price_alter_direct_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='subject',
        ),
    ]
