# Generated by Django 5.1.4 on 2025-01-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_comment_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
