# Generated by Django 5.1.4 on 2025-01-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
