# Generated by Django 5.1.4 on 2025-01-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='tex',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='tex_1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='tex_2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
