# Generated by Django 5.1.4 on 2025-01-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_jobs_bio_jobs_tex_jobs_tex_1_jobs_tex_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='tex_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
