# Generated by Django 5.1.4 on 2025-01-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_d_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direct',
            name='slug',
        ),
    ]
