# Generated by Django 5.1.4 on 2025-01-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_direct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_comment',
            name='dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_2', to='blog.direct'),
        ),
    ]
