# Generated by Django 5.1.4 on 2025-01-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_automotive_hotel_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img2',
            field=models.ImageField(default=1, upload_to='index/img'),
            preserve_default=False,
        ),
    ]
