# Generated by Django 5.1.4 on 2025-01-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_hotel_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='tex',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='tex_1',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='tex_2',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='tex_3',
        ),
    ]
